
[Pixels]
tdac = "tdac_3.csv"

# Set chip registers.
[Registers]
EnCoreCol = 18014398509481983
DAC_PREAMP_L_LIN = 300
DAC_PREAMP_R_LIN = 300
DAC_PREAMP_TL_LIN = 300
DAC_PREAMP_TR_LIN = 300
DAC_PREAMP_T_LIN = 300
DAC_PREAMP_M_LIN = 300
DAC_FC_LIN = 20
DAC_KRUM_CURR_LIN = 70
DAC_REF_KRUM_LIN = 360
DAC_COMP_LIN = 110
DAC_COMP_TA_LIN = 110
DAC_GDAC_L_LIN = 409
DAC_GDAC_R_LIN = 409
DAC_GDAC_M_LIN = 409
DAC_LDAC_LIN = 140
LEACKAGE_FEEDBACK = 0
AnalogInjectionMode = 0
CalEdgeFineDelay = 0
HitSampleMode = 1
TRIM_VREFA = 8
TRIM_VREFD = 8
VCAL_HIGH = 1700
VCAL_MED = 300
VOLTAGE_TRIM = 152

